#!/usr/bin/env node
/**
 * report.mjs — renders VERIFICATION.md from proof/verification.json and
 * proof/shots.json. Generated rather than hand-written so the published claims
 * can never drift from the last run.
 *
 *   node scripts/report.mjs
 */
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const vPath = join(ROOT, 'proof', 'verification.json');

if (!existsSync(vPath)) {
  console.error('no proof/verification.json — run `npm run verify` first');
  process.exit(1);
}

const v = JSON.parse(readFileSync(vPath, 'utf8'));
const shotsPath = join(ROOT, 'proof', 'shots.json');
const shots = existsSync(shotsPath) ? JSON.parse(readFileSync(shotsPath, 'utf8')).shots : [];

const TITLES = {
  boot: 'Boot integrity',
  scroll: 'Scroll systems',
  type: 'Kinetic typography',
  material: 'Material, depth and fallback tiers',
  carousel: 'Carousel and gesture physics',
  transitions: 'Transitions and continuity',
  smooth: 'Smooth scroll wiring',
  a11y: 'Accessibility floor',
  perf: 'Frame pacing',
};

const groups = [...new Set(v.results.map((r) => r.group))];
const p = v.framePacing;

const lines = [
  '# Verification report',
  '',
  '> Generated by `node scripts/report.mjs` from `proof/verification.json`.',
  '> Re-run `npm run proof` to regenerate everything in this file.',
  '',
  `**Result: ${v.passed}/${v.total} assertions passed** (${v.failed} failed)`,
  '',
  `- Generated: ${v.generatedAt}`,
  `- Node: ${v.node}`,
  '- Browser: headless Chromium (Playwright), software rasterisation, no GPU',
  '',
  'Each assertion below reads a measured value out of a real browser — a computed style, a',
  'bounding box, an accessible name, an element position after a pointer gesture — not the',
  'presence of code.',
  '',
];

if (p) {
  lines.push(
    '## Measured performance',
    '',
    '| Measurement | Result |',
    '| --- | --- |',
    `| Frames sampled during a full scroll-through of \`scroll.html\` | ${p.frames} |`,
    `| Median frame interval | ${p.median}ms |`,
    `| p95 frame interval | ${p.p95}ms |`,
    `| Worst frame | ${p.worst}ms |`,
    `| Long tasks while scrolling | ${p.longTasks} |`,
  );
  if (p.refraction) {
    lines.push(
      `| \`material.html\` median frame, refraction rim on chrome | ${p.refraction.withLens}ms |`,
      `| \`material.html\` median frame, rim removed | ${p.refraction.withoutLens}ms |`,
      `| Refraction cost ratio | ×${p.refraction.ratio} |`,
    );
  }
  lines.push(
    '',
    'Absolute numbers from a software-rasterised container say nothing about phone hardware.',
    'They are recorded so the *ratios* — and any regression — are visible.',
    '',
  );
}

for (const g of groups) {
  const rows = v.results.filter((r) => r.group === g);
  lines.push(
    `## ${TITLES[g] ?? g}`,
    '',
    `${rows.filter((r) => r.pass).length}/${rows.length} passed`,
    '',
    '| | Assertion | Measured |',
    '| --- | --- | --- |',
    ...rows.map((r) => `| ${r.pass ? '✅' : '❌'} | ${r.name} | ${r.detail || '—'} |`),
    '',
  );
}

if (shots.length) {
  lines.push(
    '## Screenshots',
    '',
    `${shots.length} deterministic captures in \`proof/shots/\`. Every shot lands via the`,
    '`?jump=` dev contract and waits for `__ready`, so the command is reproducible.',
    '',
    '| Shot | Page | Scroll | Viewport |',
    '| --- | --- | --- | --- |',
    ...shots.map((s) => `| \`${s.name}.png\` | ${s.path} | ${s.jump}px | ${s.viewport} |`),
    '',
  );
}

writeFileSync(join(ROOT, 'VERIFICATION.md'), lines.join('\n'));
console.log(`VERIFICATION.md written — ${v.passed}/${v.total} assertions`);
