#!/usr/bin/env node
/**
 * setup.mjs — installs the lab's runtime dependencies and copies the browser
 * builds into lab/vendor/ so every lab page runs offline.
 *
 *   node scripts/setup.mjs
 *
 * lab/vendor/ is gitignored on purpose: GSAP, Embla and Lenis are fetched from
 * npm under their own licenses instead of being redistributed inside this repo.
 * Every lab page also carries a CDN fallback, so the pages still run if you skip
 * this step while online (see lab/js/boot.js).
 */
import { execFileSync } from 'node:child_process';
import { cpSync, existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const VENDOR = join(ROOT, 'lab', 'vendor');

/** [source path inside node_modules, destination filename in lab/vendor] */
const FILES = [
  ['gsap/dist/gsap.min.js', 'gsap.min.js'],
  ['gsap/dist/ScrollTrigger.min.js', 'ScrollTrigger.min.js'],
  ['gsap/dist/SplitText.min.js', 'SplitText.min.js'],
  ['gsap/dist/Observer.min.js', 'Observer.min.js'],
  ['gsap/dist/Flip.min.js', 'Flip.min.js'],
  ['gsap/dist/Draggable.min.js', 'Draggable.min.js'],
  ['gsap/dist/InertiaPlugin.min.js', 'InertiaPlugin.min.js'],
  ['gsap/dist/CustomEase.min.js', 'CustomEase.min.js'],
  ['gsap/dist/DrawSVGPlugin.min.js', 'DrawSVGPlugin.min.js'],
  ['gsap/dist/MotionPathPlugin.min.js', 'MotionPathPlugin.min.js'],
  ['embla-carousel/embla-carousel.umd.js', 'embla-carousel.umd.js'],
  ['lenis/dist/lenis.min.js', 'lenis.min.js'],
];

function run(cmd, args) {
  execFileSync(cmd, args, { cwd: ROOT, stdio: 'inherit' });
}

if (!existsSync(join(ROOT, 'node_modules', 'gsap'))) {
  console.log('installing runtime dependencies (gsap, embla-carousel, lenis)…');
  run('npm', ['install', '--no-audit', '--no-fund', '--omit=dev']);
}

mkdirSync(VENDOR, { recursive: true });

const copied = [];
const missing = [];
for (const [from, to] of FILES) {
  const src = join(ROOT, 'node_modules', from);
  if (!existsSync(src)) {
    missing.push(from);
    continue;
  }
  cpSync(src, join(VENDOR, to));
  copied.push(to);
}

writeFileSync(
  join(VENDOR, 'README.md'),
  [
    '# lab/vendor',
    '',
    'Generated by `node scripts/setup.mjs`. Not tracked in git.',
    'Third-party browser builds are fetched from npm under their own licenses',
    '(GSAP: gsap.com/licensing, Embla: MIT, Lenis: MIT).',
    '',
    `Last generated: ${new Date().toISOString()}`,
    '',
    ...copied.map((f) => `- ${f}`),
  ].join('\n'),
);

console.log(`vendored ${copied.length} files into lab/vendor/`);
if (missing.length) {
  console.error('missing from node_modules:', missing.join(', '));
  process.exit(1);
}
